### PR TITLE
Constraints Extensibility

### PR DESCRIPTION
**Pull request by jhaesus**
Use RequestScope::Request to make constraints extensible with own methods on Request

### CODE REVIEW

**Comment by alisnic** [comment]
can you please explain the context in which this change is necessary? I am struggling to get the use-case.

**Comment by jhaesus** [comment]
For example adding a accept method on request to write something like:
```ruby
constraints accept: :json do
end
```

**Comment by alisnic** [comment]
wouldn't be easier to just break open `Request` class?

```ruby
class NYNY::Request
  def accept
  end
end

constraints accept: :json do
end
```

**Comment by jhaesus** [comment]
True, though, monkeypatching.

**Comment by alisnic** [comment]
Do you mind if I keep this open for a while? I want to explore and find out
whether we can solve this in a more elegant way

**Comment by jhaesus** [comment]
Of course I don't. And making the request class a inheritable option would be prettier.

**Comment by alisnic** [comment]
@jhaesus I thought about this for a while and I cannot come up with a good and simple API that will work. I am very thankful for you contribution, however I think that the API you are proposing is not straightforward.  From this perspective, I'd rather have users monkey-patch `Request` class instead of confusing them.

Sorry I took so long to respond. And if you disagree with me, fork `nyny`! I'm all for open source ;)

**Pull request closed without merging**
